name: Deploy Static SvelteKit app to Github Pages

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      
      - name: Install dependencies
        run: pnpm i
        
      - name: Setup Pages
        uses: actions/configure-pages@v3
        with:
          static_site_generator: "sveltekit"
      
      - name: Build site
        run: pnpm run build
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'build/'

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
